//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrmManageDbContainer : DbContext
    {
        public CrmManageDbContainer()
            : base("name=CrmManageDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionGroup> ActionGroup { get; set; }
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<AdminInfo> AdminInfo { get; set; }
        public DbSet<R_AdminInfo_ActionInfo> R_AdminInfo_ActionInfo { get; set; }
        public DbSet<R_AdminInfo_Role> R_AdminInfo_Role { get; set; }
        public DbSet<Role> Role { get; set; }
    }
}
