//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrmBusinessDb : DbContext
    {
        public CrmBusinessDb()
            : base("name=CrmBusinessDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserBaseInfo> UserBaseInfo { get; set; }
        public virtual DbSet<UserLoginInSide> UserLoginInSide { get; set; }
        public virtual DbSet<UserLoginOutSide> UserLoginOutSide { get; set; }
    }
}
