//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<R_UserInfo_Role> R_UserInfo_Role { get; set; }
        public virtual DbSet<ActionInfo> ActionInfo { get; set; }
        public virtual DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public virtual DbSet<ActionGroup> ActionGroup { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<GoodInfo> GoodInfo { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<PropOption> PropOption { get; set; }
        public virtual DbSet<GoodsPropValue> GoodsPropValue { get; set; }
        public virtual DbSet<GoodSKU> GoodSKU { get; set; }
        public virtual DbSet<ImageInfo> ImageInfo { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
    }
}
