//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodSKU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodSKU()
        {
            this.GoodsPropValue = new HashSet<GoodsPropValue>();
        }
    
        public int ID { get; set; }
        public string SkuCode { get; set; }
        public string Remark { get; set; }
        public string SKUOptions { get; set; }
        public int GoodInfoID { get; set; }
        public decimal StoreCount { get; set; }
    
        public virtual GoodInfo GoodInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsPropValue> GoodsPropValue { get; set; }
    }
}
