//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodInfo()
        {
            this.Property = new HashSet<Property>();
            this.GoodSKU = new HashSet<GoodSKU>();
            this.GoodsPropValue = new HashSet<GoodsPropValue>();
            this.Category = new HashSet<Category>();
            this.ImageInfo = new HashSet<ImageInfo>();
        }
    
        public int ID { get; set; }
        public string GoodName { get; set; }
        public string GoodNo { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public string GoodStatus { get; set; }
        public System.DateTime Subtime { get; set; }
        public System.DateTime OnShelfTime { get; set; }
        public System.DateTime OffLineTime { get; set; }
        public short GoodMark { get; set; }
        public int MainInageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodSKU> GoodSKU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsPropValue> GoodsPropValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageInfo> ImageInfo { get; set; }
    }
}
