//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.RoomRecord = new HashSet<RoomRecord>();
        }
    
        public int ID { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Cover { get; set; }
        public int OnlineCount { get; set; }
        public int TotalCount { get; set; }
        public short Status { get; set; }
        public System.DateTime InsertTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual UserBase UserBase { get; set; }
        public virtual ICollection<RoomRecord> RoomRecord { get; set; }
    }
}
