//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginInSide
    {
        public int UserId { get; set; }
        public int LoginType { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public int LoginErrorCount { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public System.DateTime InserTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
