//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBaseInfo
    {
        public int ID { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public string Avatar { get; set; }
        public string UserPhoto { get; set; }
        public int Gender { get; set; }
        public int UserLevel { get; set; }
        public int Fans { get; set; }
        public int SubScription { get; set; }
        public System.DateTime InserTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
