//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBase
    {
        public UserBase()
        {
            this.GoldRecord = new HashSet<GoldRecord>();
            this.IntegralRecord = new HashSet<IntegralRecord>();
            this.MoneyRecord = new HashSet<MoneyRecord>();
            this.Room = new HashSet<Room>();
            this.RoomRecord = new HashSet<RoomRecord>();
            this.UserFans = new HashSet<UserFans>();
        }
    
        public int ID { get; set; }
        public int LoginId { get; set; }
        public string UserNumber { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public string Avatar { get; set; }
        public string UserPhoto { get; set; }
        public int Gender { get; set; }
        public byte UserLevel { get; set; }
        public int Fans { get; set; }
        public int SubScription { get; set; }
        public short Status { get; set; }
        public string RegAddr { get; set; }
        public System.DateTime InsertTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual ICollection<GoldRecord> GoldRecord { get; set; }
        public virtual ICollection<IntegralRecord> IntegralRecord { get; set; }
        public virtual ICollection<MoneyRecord> MoneyRecord { get; set; }
        public virtual ICollection<Room> Room { get; set; }
        public virtual ICollection<RoomRecord> RoomRecord { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserLoginInSide UserLoginInSide { get; set; }
        public virtual UserLoginOutSide UserLoginOutSide { get; set; }
        public virtual ICollection<UserFans> UserFans { get; set; }
    }
}
